apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: nacosdemo
  labels:
    app: order-service
spec:
  ports:
    - name: http
      port: 8082
      protocol: TCP
      targetPort: 8082
  selector:
    app: order-service
#  type: ClusterIP
  type: NodePort
