
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "datakit.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "datakit.fullname" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
    - port: 8125
      targetPort: 8125
      protocol: UDP
      name: statsd

