apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: nacosdemo
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: public.ecr.aws/q1p2c6o9/awsdemo/user_service:latest
          ports:
            - containerPort: 8081
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          env:
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: DD_AGENT_HOST
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.hostIP
          envFrom:
            - configMapRef:
                name: nacosdemo-config

          volumeMounts:
            - name: log-path
              mountPath: /var/log/
      volumes:
        - name: log-path
          hostPath:
            path: /var/log/

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: nacosdemo
  labels:
    app: user-service
spec:
  ports:
    - name: http
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: user-service
  #  type: ClusterIP
  type: NodePort
