## java -jar spring-boot.jar --spring.profiles.active=prod
##  scheduledtime 1000 * 60 * 5

server:
  port: 8082
spring:
  application:
    name: order-service
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: 127.0.0.1:8848
        register-enabled: true

      config:
        enabled: true
        file-extension: properties
        server-addr: 127.0.0.1:8848
  cache:
    type: redis
    cache-names: redisCache
    redis:
      time-to-live: 0
      cache-null-values: true
      use-key-prefix: true

  datasource:
    url: jdbc:mysql://localhost:3306/guancedb?useSSL=false&allowPublicKeyRetrieval=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 1

  redis:
    host: localhost
    database: 0
    port: 6379


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#logging:
#  level:
#    org.awsdemo.order.dal.Mapper: debug


#logging:
#  file:
#    path: ./logs/awsdemo/${spring.application.name}










