## java -jar spring-boot.jar --spring.profiles.active=prod
##  scheduledtime 1000 * 60 * 5


server:
  port: 8081

spring:
  application:
    name: user-service

#nacos:
#  config:
#    server-addr: 127.0.0.1:8848
#    context-path: nacos
#    data-id: user-svr
#    auto-refresh: true
#    bootstrap:
#      enable: true

