## java -jar spring-boot.jar --spring.profiles.active=prod
##  scheduledtime 1000 * 60 * 5

server:
  port: 8082
spring:
  application:
    name: order-service
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr:  192.168.16.166:8848
        register-enabled: true
      config:
        enabled: true
        file-extension: properties
        server-addr:  192.168.16.166:8848

logging:
  file:
    path: ./logs/awsdemo/${spring.application.name}