## java -jar spring-boot.jar --spring.profiles.active=prod
##  scheduledtime 1000 * 60 * 5

server:
  port: 8082
spring:
  application:
    name: order-service
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: 127.0.0.1:8848
        register-enabled: true
        group: demo
      config:
        enabled: false
        file-extension: properties
        server-addr: 127.0.0.1:8848
        group: demo

logging:
  file:
    path: ./logs/awsdemo/${spring.application.name}










