apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

vpc:
  id: "vpc-05b22a6d04b23743e"
  subnets:
    private:
      ap-southeast-1a: { id: subnet-032ee7949376c2d28 }
      ap-southeast-1b: { id: subnet-086153be01f32ae47 }
    public:
      ap-southeast-1a: { id: subnet-0bfe7739a0942a4af }
      ap-southeast-1b: { id: subnet-008a67adc08e6658c }

metadata:
  name: eks-workshop01
  region: ap-southeast-1
  version: '1.30'

iam:
  withOIDC: true # required


managedNodeGroups:
  - name: managed-ng-1
    instanceType: m6i.xlarge
    desiredCapacity: 3
    minSize: 3
    maxSize: 3
    ssh:
      allow: true
      publicKeyName: kevin-poc-sgs-1
    privateNetworking: true
    ebs_optimized: true




cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
    logRetentionInDays: 7
